### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by Maknee** [jarwino/snag-yosemite-reservation#1]
@jarwino 

Might be worth putting some documentation here for future extensibility

```
# CHECK IF THE DAMN TICKET IS AVALIABLE
driver.get("https://www.recreation.gov/timed-entry/10086745/ticket/10086746")
```

**Comment by liamdugan** [comment]
+1 to this, without these sorts of comments the code might be a bit difficult for others to extend

**Comment by jarwino** [comment]
I believe the code explains itself and thus requires no further documentation.
